### ISSUE TITLE
Arch AUR Package

### ISSUE THREAD

**Issue by Strikingwolf** [Kansattica/msync#36]
I'm in the process of packaging this up in the AUR for Arch Linux. In doing so I remembered an error I have while using msync that doesn't cause any problems but might be confusing to a user.

Do you know what might be causing this error message:
`msync: /usr/lib/libcurl-gnutls.so.4: no version information available (required by msync)`

Also are you ok with me maintaining an AUR package for your program?

**Comment by Kansattica** [comment]
First of all, go for it!

Second of all, hm. Are you using one of the prebuilt binaries from the releases page? A little searching says that this can happen when the version of libcurl you're using wasn't built with versioned symbols, which the libcurl on the CI machines was (Ubuntu, apparently, includes special versioning information in their libcurl that can also cause problems). If this is the case, I could try releasing a version that statically links libcurl, but dynamically links the TLS library.

The output of readelf starting at line 676 here: https://travis-ci.org/github/Kansattica/msync/jobs/685175676 might help if you compare it to what you get on your own system.

Does the issue happen if you build msync yourself?

**Comment by Strikingwolf** [comment]
I am using the prebuilt binaries! I just found an AUR package that fixes libcurl's versioning stuff. I need to do some more PKGBUILD stuff since this is an AUR package which can be a little bit harder to work with as a dependency.

The issue doesn't happen if I build msync myself. Due to that I'll probably package up a version that builds the executable itself before I do the binary release. Generally AUR packages come in both flavors for those types of people that like to build things themselves.

Thanks for the help!

**Comment by Strikingwolf** [comment]
The [msync-git](https://aur.archlinux.org/packages/msync-git/) package is now up on the AUR!

I'll work on the binary package later

**Comment by Kansattica** [comment]
Good to hear you got that fixed! Thank you for reaching out.

If this is to be an installed, systemwide package, I would suggest running CMake like this:

```
cmake .. -DCMAKE_BUILD_TYPE=Release -DMSYNC_BUILD_TESTS=OFF -DMSYNC_USER_CONFIG=ON -DMSYNC_FILE_LOG=OFF
```

This is how the binaries that have "install" in the name are configured- they respect XDG_CONFIG_HOME if set and put config files in `~/.config/msync` if it isn't, which is a little more fitting for something that's going to be installed systemwide. This might become the default configuration in the future, perhaps when msync hits version 1.0.

**Comment by Strikingwolf** [comment]
Yeah I noticed that from testing stuff out and fixed it :+1:

**Comment by Strikingwolf** [comment]
And the binary package is up [msync-git](https://aur.archlinux.org/packages/msync/)! I'll try to update it whenever you release new versions. If you need to shoot me an email to yell at me about it you can try justalittleepsilon@gmail.com

There's also my fedi account over at faye@catgirl.science

**Comment by Kansattica** [comment]
Thanks for doing this! I'm gonna go ahead and close this issue, and I'll see about adding links to the packages to the readme when I'm more awake.
