### ISSUE TITLE
JSON error 302 on authentification for pleroma

### ISSUE THREAD

**Issue by satak-azat** [Kansattica/msync#60]
When I try to connect to a pleroma instance I get the following message : 

`msync new --account user@soc.luciferi.st
Reading accounts from "/home/satak/.config/msync/msync_accounts"
Matched account user@soc.luciferi.st
Existing user found.
Registering app with soc.luciferi.st.
An error occurred: [json.exception.type_error.302] type must be string, but is null
For account: user@soc.luciferi.st
`

I've tried to connect on 3 different pleroma instances (soc.luciferi.st, soc.punktrash.club and queer.hacktivis.me) with the same error on all, I've had no problem on mastodon instances tho. I kinda understand it has to do with the response of pleroma on authentication which must be formated differently than the one from mastodon but I don't know how to workaround this myself.

**Comment by Kansattica** [comment]
I believe PR #52 fixed this. If the problem isn't resolved by building from source or downloading a more recent build (https://github.com/Kansattica/msync/actions/runs/585979667 should do), let me know.

**Comment by satak-azat** [comment]
Resolved using the build you linked, thank you very much.
